script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
dataset_name="OAF_BrC_CRC_prostate_non_avdb"
cmd="pyCMM-cmmdb-cal-mut-stat "
cmd+=" -j $script_dir/cal_mut_stat_"$dataset_name"_jobs_setup.txt"
#cmd+=" -l /proj/b2011117/private/projects/out/db/cal_stat_101CRC_all/101CRC_all"
eval "$cmd"
