script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cmd="pyCMM-cmmdb-cal-mut-stat "
cmd+=" -j $script_dir/cal_mut_stat_101CRC_CAFAM_jobs_setup.txt"
cmd+=" -l /proj/b2011117/private/projects/out/db/cal_stat_101CRC_CAFAM/101CRC_CAFAM"
eval "$cmd"
